{{- if and .Values.redis.enabled .Values.opentelemetry.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-seed
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dapr-agents.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: seed
        image: "{{ .Values.redis.image }}:{{ .Values.redis.tag }}"
        env:
        - name: REDIS_HOST
          value: {{ printf "%s.%s.svc.cluster.local" .Values.redisConfig.serviceName .Release.Namespace }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redisConfig.passwordSecret.name }}
              key: {{ .Values.redisConfig.passwordSecret.key }}
        command:
        - sh
        - -c
        - |
          AUTH=""
          if [ -n "$REDIS_PASSWORD" ]; then AUTH="-a $REDIS_PASSWORD"; fi
          until redis-cli -h "$REDIS_HOST" $AUTH ping | grep -q PONG; do
            echo "Waiting for Redis..."
            sleep 2
          done
          {{- $otelEndpoint := printf "http://%s" .Values.opentelemetry.endpoint }}
          redis-cli -h "$REDIS_HOST" $AUTH HSET agent_runtime \
            version 1 \
            data '{"OTEL_ENABLED":"true","OTEL_ENDPOINT":"{{ $otelEndpoint }}","OTEL_LOGGING_ENABLED":"true","OTEL_TRACING_ENABLED":"true","OTEL_LOGGING_EXPORTER":"otlp_grpc","OTEL_TRACING_EXPORTER":"otlp_grpc"}'
          echo "Seeded agent_runtime hash"
{{- end }}
