{{- if .Values.appSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dapr-agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.appSecrets }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
{{- end }}
