---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dapr-agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key-safe-external-service: |
    {
      "key_id": {{ .Values.secrets.apiKeySafe.keyId | quote }},
      "token_value": {{ .Values.secrets.apiKeySafe.tokenValue | quote }},
      "expiry": {{ .Values.secrets.apiKeySafe.expiry | quote }}
    }
  database-credentials: |
    {
      "username": {{ .Values.secrets.database.username | quote }},
      "password": {{ .Values.secrets.database.password | quote }},
      "connection_string": {{ .Values.secrets.database.connectionString | quote }}
    }
  agent-configuration: |
    {
      "log_level": {{ .Values.secrets.agentConfig.logLevel | quote }},
      "max_retries": {{ .Values.secrets.agentConfig.maxRetries | quote }},
      "cache_ttl_seconds": {{ .Values.secrets.agentConfig.cacheTtlSeconds | quote }}
    }
