apiVersion: v1
kind: Secret
metadata:
  name: kagent-openai
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dapr-agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.llm.apiKey | default .Values.kagent.providers.openAI.apiKey | quote }}
