apiVersion: v1
kind: Secret
metadata:
  name: llm-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dapr-agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.llm.apiKey | quote }}
